# Generated by Django 2.2.28 on 2023-03-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230317_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
